### ISSUE TITLE
不支持 APNG

### ISSUE THREAD

**Issue by umlearn** [kyleduo/TinyPNG4Mac#21]
开发大哥好，Tinypng 官方以提供压缩 apng (动态png)功能，可是 Mac 版尝试后无法压缩，可以跟进下这个问题么？

**Comment by kyleduo** [comment]
我试了下是支持的，客户端没有对图片做任何处理。如果客户端不行的话可以在官网上试一下。方便的话可以提供下图片，我有空试试。

**Comment by umlearn** [comment]
现在确实可以了～ 之前可能是官方 API 没有支持 Apng...
