### ISSUE TITLE
Where is 1.0.1 compiled?

### ISSUE THREAD

**Issue by jrgong420** [kyleduo/TinyPNG4Mac#31]
https://github.com/kyleduo/TinyPNG4Mac/releases

Where is the compiled version for MacOSX?

Only 1.0.0 currently has a link with the compiled one

**Comment by kyleduo** [comment]
Sorry, there was some issue when uploading binary file to Github. Use this download link instead, please. [Download](https://static.kyleduo.com/project/release/tinypng4mac/tinypng4mac_1_0_1.app.zip)

**Comment by kyleduo** [comment]
Hey, I've finally successfully uploaded the binary. And I'll close this issue.

Sorry again.
