### ISSUE TITLE
feature demand: add "export as base64"

### ISSUE THREAD

**Issue by teamrun** [kyleduo/TinyPNG4Mac#4]
it's great! i use tinypng.com a lot, i dreamed about an app like this!

a feature demand: could you add  "export as base64" in this app? Most of the time after compressing imgs, i drag them to https://www.base64-image.de/ and paste the result in my css or html file. 

中文: 很棒的 app! 我平时也经常用 tinypng 来压缩图片, 也曾想过做个这样的 app 出来.

提一个需求: 能否给 app 增加一个"导出 base64"的功能? 很多时候我压缩完图片之后做的下一步就是拖到 base64的网站里去, 把结果贴到 css 或者 html 文件中.(很多时候压缩的图片都是图标类的小图, base64放文件里减少请求)

**Comment by kyleduo** [comment]
这个功能短期内不会开发。我希望TinyPNG4Mac能足够简洁。
