### ISSUE TITLE
{"error":"Not found","message":"Resource not found or expired."}

### ISSUE THREAD

**Issue by Philtky** [kyleduo/TinyPNG4Mac#41]
Hi!
First of all, thank you for this very useful tiny app.

I realized today that all my PNGs are coming back as a 64kb file (same file name and extension as the original file) but no image at all.

Inside this file I find this text `{"error":"Not found","message":"Resource not found or expired."}`

My API usage is still ok (186 / 500) and the files are compressing well thru the TinyPNG website.

Any clue on the problem?

Thank you!

Phil

OsX 10.15.4 
TinyPNG4Mac Version 1.0.4 (12)

**Comment by kyleduo** [comment]
I tried but the problem not present. But I'll add validation to following version.
I think there may be a problem with tinypng's service. Could you please try again later?

**Comment by Philtky** [comment]
Ok! Thanks a lot.

I’ll try later and keep you in touch!

Thanks again,



Phil

**Comment by Philtky** [comment]
Everything's working normally this morning!
As you said, it was certainly a temporary problem with the tinypng's service.

Thanks again for your quick replies.

Best,
Phil

**Comment by kyleduo** [comment]
Glad to hear that. You're welcome.

Have a nice day~
