### ISSUE TITLE
Apple Silicon or Universal App Version?

### ISSUE THREAD

**Issue by sparkktv** [kyleduo/TinyPNG4Mac#46]
Is there any chance of getting an update that runs this natively on M1 machines instead of using Rosetta?

**Comment by yy523697597** [comment]
Yes, I really want to run this app natively. Please update the app

**Comment by limuyang2** [comment]
I have submitted the new code, waiting for the author to merge

**Comment by kyleduo** [comment]
A new release can be found on the [release page](https://github.com/kyleduo/TinyPNG4Mac/releases/tag/v1.0.5). Thanks for the contribution. @limuyang2
