### ISSUE TITLE
能添加个命令行版本么  

### ISSUE THREAD

**Issue by yingnierxiao** [kyleduo/TinyPNG4Mac#5]
能添加个命令行版本么

**Comment by kyleduo** [comment]
建议你自己动手:)

**Comment by liyang85** [comment]
有现成的：https://www.npmjs.com/package/tinypng-cli

安装：`npm install -g tinypng-cli`

支持的功能很全面：

- 压缩当前目录下所有图片：`tinypng .`
- 递归压缩子目录：`tinypng -r`
- 压缩单个目录：`tinypng assets/img`
- 压缩多个目录：`tinypng assets/img1 assets/img2`
- 压缩单张图片：`tinypng assets/img/demo.png`
- 压缩多张图片：`tinypng assets/img/demo1.png assets/img/demo2.png`
- 单独指定API key：`tinypng demo.png -k E99a18c4f8cb3EL5f2l08u368_922e03`
