### ISSUE TITLE
建议支持 WebP

### ISSUE THREAD

**Issue by iDvel** [kyleduo/TinyPNG4Mac#50]
官网已经支持啦

**Comment by GwynethLlewelyn** [comment]
Indeed 😭  It seems that this project is not being actively maintained any longer...

**Comment by kyleduo** [comment]
I'll do the support within next week.

**Comment by kyleduo** [comment]
1.0.6 has been released.

**Comment by GwynethLlewelyn** [comment]
Yay \o/ Thanks :-)
