### ISSUE TITLE
v 1.0.6 does not run on Intel Macs

### ISSUE THREAD

**Issue by core-code** [kyleduo/TinyPNG4Mac#53]
is this on purpose?

<img width="257" alt="Screenshot 2023-11-14 at 20 26 27" src="https://github.com/kyleduo/TinyPNG4Mac/assets/1261954/f46364c2-591d-40c0-91d2-371ae72445ed">

**Comment by GwynethLlewelyn** [comment]
Uh-oh... I'm still on an Intel Mac... I guess I'll have to wait a bit before installing the latest version!

**Comment by kyleduo** [comment]
Sorry, this is a mistake. I'll fix this.

**Comment by kyleduo** [comment]
Please check out the [latest release 1.0.7](https://github.com/kyleduo/TinyPNG4Mac/releases/tag/v1.0.7). The problem has been fixed. Sorry for the trouble.
