### ISSUE TITLE
Feature request: Drag and drop files on Dock icon

### ISSUE THREAD

**Issue by swinggraphics** [kyleduo/TinyPNG4Mac#56]
Thank you for this super useful app! I use it all the time, and the one point of frustration I have is needing to activate the app, potentially move TinyPNG's window if the files I want are now covered up, and drag files into the window. On a busy day, it's actually a lot of extra clicks and mouse movement. It would be great to be able to drag files onto the Dock icon. Cheers.

**Comment by kyleduo** [comment]
Thanks. Version 2.0 supports this feature.

**Comment by swinggraphics** [comment]
Wonderful, thank you!!! I like the cute new icon too ☺️
