### ISSUE TITLE
Overwrite original

### ISSUE THREAD

**Issue by alexcroox** [kyleduo/TinyPNG4Mac#7]
This app is fantastic thank you, one suggestion for improvement is how [ImageOptim](https://imageoptim.com/mac) allows you to simply drag your images in and it saves back over them in their original paths. This means no extra work is required, you simply drag in your images from any folders and you don't need to manually manage putting them back in the right place.

**Comment by CraftizLtd** [comment]
+1 !!!! Any updates?

**Comment by kyleduo** [comment]
Yep! It’s already supported.
